# q4 Higher or Lower.

# The game will first generate a number 1 to 100 inclusively, then it will ask the player if the next number generated by the computer/program will be higher or lower.

# To win: 5 times in a row
# to lose: lose 5 times

# Setup
from random import randrange
cpu_num = randrange(1,101)

# IPO
game_loop = True
win_counter = 0
loss_counter = 0

while game_loop:
    print('The computer generated:', cpu_num)
    player = input('Will the next be higher or lower? (H/L): ')

    new_cpu_num = randrange(1,101)
    print('The next number was:', new_cpu_num)
    print('----')

    if new_cpu_num > cpu_num and player == 'H':
        win_counter += 1
    elif new_cpu_num < cpu_num and player == 'L':
        win_counter += 1
    else:
        loss_counter += 1
        win_counter = 0
        # this resets to 0 because the player needs to guess 5 times in a row

    cpu_num = new_cpu_num # reset cpu_num with the newest number generated

    if loss_counter == 5 or win_counter == 5:
        game_loop = False # game has ended
# end of while loop

if win_counter == 5:
    print('You win the game!')
else:
    print('You lose!')
